### ISSUE TITLE
@delon/util ArrayService arrToTreeNode 🐞🐞🐞

### ISSUE THREAD

**Issue by bucengfangqi** [ng-alain/ng-alain#2009]
### Reproduction link
[https://stackblitz.com/edit/angular-snrhrp?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-snrhrp?file=src/app/app.component.ts)

### Steps to reproduce
https://ng-alain.com/util/array/zh

### What is expected?
The first time the tree form is selected, the component will report no errors

### What is actually happening?
The first time the tree form is selected, the component will report errors

| Environment | Info |
|---|---|
| ng-alain | 11.10.2 |
| Browser | Google Chrome 91.0.4472.77 |

https://user-images.githubusercontent.com/22071679/120756506-e62a2580-c541-11eb-87e6-4f85e0e7e74e.mp4

**Comment by cipchk** [comment]
Since ajv 8.x began to restrict the Schema strictly, using `arrToTreeNode` will generate a lot of redundant information and cause the `Maximum call stack size exceeded` exception (you can get exception detail by turning on the `debug` option).

So, recommended that the value of `enum` is a simple data type, like this:

```ts
this.arrayService.arrToTreeNode([
          { title: '待支付', id: 'WAIT_BUYER_PAY' },
          { title: '已支付', id: 'TRADE_SUCCESS' },
          { title: '交易完成', id: 'TRADE_FINISHED' }
        ]).map(i => ({ key: i.key, title: i.title }))
```

> BTW, If any Schema don't expect, you can get exception information through the `debug` option.
